# Generated by Django 5.2.4 on 2025-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_stripe_price_id_event_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('checked_in', 'Checked In'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
